# Generated by Django 5.1.7 on 2025-03-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artlcle',
            new_name='article',
        ),
    ]
